<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-project</artifactId>
    <version>12.1.7-SNAPSHOT</version>
  </parent>
  <groupId>org.eclipse.jetty.eecommon</groupId>
  <artifactId>jetty-eecommon</artifactId>
  <packaging>pom</packaging>
  <name>EE Common</name>

  <modules>
    <module>jetty-eecommon-annotations</module>
    <module>jetty-eecommon-apache-jsp</module>
    <module>jetty-eecommon-bom</module>
    <module>jetty-eecommon-cdi</module>
    <module>jetty-eecommon-demos</module>
    <module>jetty-eecommon-fcgi-proxy</module>
    <module>jetty-eecommon-glassfish-jstl</module>
    <module>jetty-eecommon-home</module>
    <module>jetty-eecommon-jaspi</module>
    <module>jetty-eecommon-jndi</module>
    <module>jetty-eecommon-jspc-maven-plugin</module>
    <module>jetty-eecommon-maven-plugin</module>
    <module>jetty-eecommon-osgi</module>
    <module>jetty-eecommon-plus</module>
    <module>jetty-eecommon-proxy</module>
    <module>jetty-eecommon-quickstart</module>
    <module>jetty-eecommon-servlet</module>
    <module>jetty-eecommon-servlets</module>
    <module>jetty-eecommon-tests</module>
    <module>jetty-eecommon-webapp</module>
    <module>jetty-eecommon-websocket</module>
  </modules>

  <properties>

    <eecommon.jakarta.activation.api.version>2.1.3</eecommon.jakarta.activation.api.version>
    <eecommon.jakarta.mail.api.version>2.1.3</eecommon.jakarta.mail.api.version>
    <eecommon.jakarta.servlet.api.version>6.1.0</eecommon.jakarta.servlet.api.version>
    <eecommon.jakarta.servlet.jsp.api.version>4.0.0</eecommon.jakarta.servlet.jsp.api.version>
    <eecommon.jakarta.servlet.jsp.jstl.impl.version>4.0.0</eecommon.jakarta.servlet.jsp.jstl.impl.version>
    <eecommon.jakarta.xml.bind.api.version>4.0.5</eecommon.jakarta.xml.bind.api.version>
    <eecommon.jakarta.xml.bind.impl.version>4.0.6</eecommon.jakarta.xml.bind.impl.version>
    <eecommon.jakarta.xml.jaxws.impl.version>4.0.2</eecommon.jakarta.xml.jaxws.impl.version>
    <eecommon.jersey.version>4.0.2</eecommon.jersey.version>
    <eecommon.jsp.impl.version>11.0.10.1</eecommon.jsp.impl.version>
    <eecommon.mail.impl.version>2.0.2</eecommon.mail.impl.version>
    <eecommon.weld.version>6.0.4.Final</eecommon.weld.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-bom</artifactId>
        <version>${eecommon.jakarta.bom.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.sun.mail</groupId>
        <artifactId>jakarta.mail</artifactId>
        <version>${eecommon.mail.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-rt</artifactId>
        <version>{eecommon.jakarta.xml.jaxws.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>jakarta.xml.bind</groupId>
        <artifactId>jakarta.xml.bind-api</artifactId>
        <version>${eecommon.jakarta.xml.bind.api.version}</version>
      </dependency>
      <!-- Jetty EECommon Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-annotations</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-apache-jsp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-cdi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-fcgi-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-glassfish-jstl</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jaspi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jndi</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jspc-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-maven-plugin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-plus</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-proxy</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-quickstart</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-servlets</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.demos</groupId>
        <artifactId>jetty-eecommon-demo-proxy-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jetty-client-webapp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jetty-server</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-servlet</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>${eecommon.jakarta.xml.bind.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
        <version>${eecommon.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
        <version>${eecommon.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-json-binding</artifactId>
        <version>${eecommon.jersey.version}</version>
      </dependency>
      <dependency>
        <groupId>org.glassfish.wasp</groupId>
        <artifactId>wasp</artifactId>
        <version>${eecommon.jakarta.servlet.jsp.jstl.impl.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.weld.servlet</groupId>
        <artifactId>weld-servlet-core</artifactId>
        <version>${eecommon.weld.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-el</artifactId>
        <version>${eecommon.jsp.impl.version}</version>
      </dependency>
      <!-- Jakarta EECommon Dependencies -->
      <dependency>
        <groupId>org.mortbay.jasper</groupId>
        <artifactId>mortbay-apache-jsp</artifactId>
        <version>${eecommon.jsp.impl.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
