<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.eclipse.jetty.eecommon</groupId>
    <artifactId>jetty-eecommon</artifactId>
    <version>12.1.7-SNAPSHOT</version>
  </parent>

  <artifactId>jetty-eecommon-bom</artifactId>
  <packaging>pom</packaging>
  <name>EECommon :: BOM</name>
  <description>Jetty EECommon APIs BOM artifact</description>

  <dependencyManagement>
    <dependencies>
      <!-- Jetty EECommon Dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-annotations</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-apache-jsp</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-cdi</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-fcgi-proxy</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-glassfish-jstl</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jaspi</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jndi</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-jspc-maven-plugin</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-maven-plugin</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-plus</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-proxy</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-quickstart</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-servlet</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-servlets</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon</groupId>
        <artifactId>jetty-eecommon-webapp</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.osgi</groupId>
        <artifactId>jetty-eecommon-osgi-alpn</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.osgi</groupId>
        <artifactId>jetty-eecommon-osgi-boot</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.osgi</groupId>
        <artifactId>jetty-eecommon-osgi-boot-jsp</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-client</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-client-webapp</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-common</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jakarta-server</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jetty-client-webapp</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-jetty-server</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.eecommon.websocket</groupId>
        <artifactId>jetty-eecommon-websocket-servlet</artifactId>
        <version>12.1.7-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>flatten-clean</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>clean</phase>
          </execution>
          <execution>
            <id>flatten</id>
            <goals>
              <goal>flatten</goal>
            </goals>
            <phase>process-resources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
